import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ActiveThemeProvider } from "@/components/active-theme";
import { cookies } from "next/headers";
import { cn } from "@/lib/utils";
import { UserProvider } from "@/contexts/UserContext";
import { LocaleProvider } from "@/contexts/LocaleContext";
import RouteProgress from "@/components/RouteProgress";

export const metadata: Metadata = {
  title: "Office Archived",
  description: "Generated by Hakimi Group",
  icons: {
    icon: "/favicon2.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const activeThemeValue = cookieStore.get("active_theme")?.value;
  const isScaled = activeThemeValue?.endsWith("-scaled");
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var locale = localStorage.getItem('app_locale') || 'en';
                  var rtl = locale === 'ps' || locale === 'fa';
                  document.documentElement.lang = locale;
                  document.documentElement.dir = rtl ? 'rtl' : 'ltr';
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={cn(
          "bg-background overscroll-none font-sans antialiased",
          activeThemeValue ? `theme-${activeThemeValue}` : "",
          isScaled ? "theme-scaled" : ""
        )}
      >
        <RouteProgress />
        <LocaleProvider>
          <UserProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              enableColorScheme
            >
              <ActiveThemeProvider initialTheme={activeThemeValue}>
                <main>{children}</main>
                <Toaster position="top-right" />
              </ActiveThemeProvider>
            </ThemeProvider>
          </UserProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
